version: "3.7"
services:
    url-shortener:
        build: url-shortener
        container_name: url-shortener
    redis:
        image: redis
        hostname: redis
        volumes: 
            - redis_volume:/data
    # optional
    redis-commander:
        image: rediscommander/redis-commander:latest
        restart: always
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
        - "8081:8081"
volumes:
    redis_volume: