version: "3.7"
services:
    url-shortener:
        build: ./url-shortener
        container_name: url-shortener
        environment:
            POSTGRES_PASSWORD: admin
            CONFIG_PATH: /app/pkg/config/dev.json
        ports:
            - 8080:8080
    postgres:
        image: postgres
        restart: always
        container_name: postgres
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin # obviously not the best
            POSTGRES_DB: url_shortener
        ports:
            - 5432:5432
        volumes:
            - postgres_volume:/var/lib/postgresql/data
    # totally optional
    adminer:
        image: adminer
        restart: always
        container_name: adminer
        ports:
            - 8081:8080
volumes:
    postgres_volume:
